# Generated by Django 5.2.8 on 2026-04-28 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(choices=[('NGN', 'Nigerian Naira')], default='NGN', max_length=3),
        ),
    ]
