# Generated by Django 5.2.8 on 2026-06-01 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_payment_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='pi_payment_id',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='payment',
            name='pi_txid',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='payment',
            name='pi_username',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(choices=[('NGN', 'Nigerian Naira'), ('PI', 'Pi')], default='NGN', max_length=3),
        ),
    ]
