# Generated by Django 5.2.8 on 2025-11-26 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addon_type', models.CharField(choices=[('deep_cleaning', 'Deep Cleaning (+₦5,000)'), ('window_cleaning', 'Window Cleaning (+₦3,000)'), ('carpet_cleaning', 'Carpet Cleaning (+₦2,000)'), ('emergency', 'Emergency Service (24/7) (+₦10,000)')], max_length=30, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=10000.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='service',
            options={},
        ),
        migrations.RemoveField(
            model_name='service',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='service',
            name='duration_hours',
        ),
        migrations.RemoveField(
            model_name='service',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('cleaning services', 'Cleaning Services'), ('fumigation services', 'Fumigation Services'), ('laundry services', 'Laundry Services')], max_length=50),
        ),
        migrations.CreateModel(
            name='CleaningServiceOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleaning_type', models.CharField(choices=[('residential cleaning', 'Residential Cleaning'), ('commercial cleaning', 'Commercial Cleaning')], max_length=30)),
                ('property_size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('commercial space', 'Commercial Space')], max_length=30)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleaning_services', to='services.service')),
            ],
        ),
        migrations.CreateModel(
            name='FumigationServiceOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('commercial space', 'Commercial Space')], max_length=30)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fumigation_services', to='services.service')),
            ],
        ),
        migrations.CreateModel(
            name='LaundryServiceOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laundry_services', to='services.service')),
            ],
        ),
        migrations.CreateModel(
            name='RecurringBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_locations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('additional_services', models.ManyToManyField(blank=True, to='services.additionalservice')),
                ('main_service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='services.service')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='services.schedule')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='services.servicelocation')),
            ],
        ),
        migrations.AddField(
            model_name='schedule',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.timeslot'),
        ),
        migrations.DeleteModel(
            name='ServicePricing',
        ),
        migrations.AddConstraint(
            model_name='cleaningserviceoption',
            constraint=models.UniqueConstraint(fields=('service', 'cleaning_type', 'property_size'), name='unique_cleaning_service_option'),
        ),
        migrations.AddConstraint(
            model_name='fumigationserviceoption',
            constraint=models.UniqueConstraint(fields=('service', 'property_size'), name='unique_fumigation_service_option'),
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('date', 'slot')},
        ),
    ]
