# Generated by Django 5.2.8 on 2025-12-22 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_additionalservice_schedule_timeslot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fumigationserviceoption',
            name='service',
        ),
        migrations.RemoveField(
            model_name='laundryserviceoption',
            name='service',
        ),
        migrations.RemoveField(
            model_name='recurringbooking',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='slot',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='schedule',
        ),
        migrations.AlterField(
            model_name='booking',
            name='main_service',
            field=models.CharField(choices=[('cleaning services', 'Cleaning Services'), ('fumigation services', 'Fumigation Services'), ('laundry services', 'Laundry Services')], default='', max_length=30),
        ),
        migrations.RemoveField(
            model_name='servicelocation',
            name='user',
        ),
        migrations.AlterField(
            model_name='booking',
            name='location',
            field=models.CharField(choices=[('victoria-island', 'Victoria Island'), ('lekki-phase1', 'Lekki Phase 1'), ('lekki-phase2', 'Lekki Phase 2'), ('ikeja-gra', 'Ikeja GRA'), ('ikoyi', 'Ikoyi'), ('surulere', 'Surulere'), ('yaba', 'Yaba'), ('other', 'Other')], default='', max_length=30),
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='booked_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='additionalservice',
            name='addon_carpet_cleaning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='additionalservice',
            name='addon_deep_cleaning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='additionalservice',
            name='addon_window_cleaning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='additionalservice',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='additionalservice',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='additionalservice',
            name='is_emergency',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='additionalservice',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='booking',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='cleaning_type',
            field=models.CharField(blank=True, choices=[('residential', 'Residential Cleaning'), ('commercial', 'Commercial Cleaning')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('paypal', 'PayPal'), ('bank_transfer', 'Bank Transfer')], default='debit_card', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='property_size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('commercial space', 'Commercial Space')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='booking',
            name='recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='recurring_interval',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='service_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='special_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='CleaningServiceOption',
        ),
        migrations.DeleteModel(
            name='FumigationServiceOption',
        ),
        migrations.DeleteModel(
            name='LaundryServiceOption',
        ),
        migrations.DeleteModel(
            name='RecurringBooking',
        ),
        migrations.DeleteModel(
            name='TimeSlot',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='ServiceLocation',
        ),
    ]
