# Generated by Django 5.2.8 on 2026-04-19 02:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_remove_fumigationserviceoption_service_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additionalservice',
            options={'ordering': ['addon_type']},
        ),
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='additionalservice',
            name='addon_carpet_cleaning',
        ),
        migrations.RemoveField(
            model_name='additionalservice',
            name='addon_deep_cleaning',
        ),
        migrations.RemoveField(
            model_name='additionalservice',
            name='addon_window_cleaning',
        ),
        migrations.RemoveField(
            model_name='additionalservice',
            name='is_emergency',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='booking',
            name='addons_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='additionalservice',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='additionalservice',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='additionalservice',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='service_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
