# Generated by Django 5.2.8 on 2026-04-24 14:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_additionalservice_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='recurring',
            new_name='is_recurring',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='phone',
        ),
        migrations.AddField(
            model_name='booking',
            name='emergency_charge',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_emergency',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='phone_number',
            field=models.CharField(default='0000000000', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='time_slot',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='additionalservice',
            name='addon_type',
            field=models.CharField(choices=[('deep_cleaning', 'Deep Cleaning (+₦5,000)'), ('window_cleaning', 'Window Cleaning (+₦3,000)'), ('carpet_cleaning', 'Carpet Cleaning (+₦2,000)')], max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='main_service',
            field=models.CharField(choices=[('cleaning', 'Cleaning Services'), ('fumigation', 'Fumigation Services'), ('laundry', 'Laundry Services')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='property_size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='', max_length=50),
        ),
    ]
