# Generated by Django 5.2.8 on 2026-04-24 15:03
from django.db import migrations
from decimal import Decimal


def seed_additional_services(apps, schema_editor):
    AdditionalService = apps.get_model('services', 'AdditionalService')  # ← your actual app name
    
    services = [
        {
            'addon_type': 'deep_cleaning',
            'name': 'Deep Cleaning',
            'price': Decimal('5000.00'),
            'description': 'Thorough deep cleaning of all surfaces.',
        },
        {
            'addon_type': 'window_cleaning',
            'name': 'Window Cleaning',
            'price': Decimal('3000.00'),
            'description': 'Professional cleaning of all windows, inside and out.',
        },
        {
            'addon_type': 'carpet_cleaning',
            'name': 'Carpet Cleaning',
            'price': Decimal('2000.00'),
            'description': 'Deep cleaning and stain removal for carpets and rugs.',
        },
    ]
    
    for service in services:
        AdditionalService.objects.get_or_create(
            addon_type=service['addon_type'],
            defaults=service
        )


def reverse_seed(apps, schema_editor):
    AdditionalService = apps.get_model('services', 'AdditionalService')
    AdditionalService.objects.filter(
        addon_type__in=['deep_cleaning', 'window_cleaning', 'carpet_cleaning']
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
            ('services', '0005_rename_recurring_booking_is_recurring_and_more'),
        ]

    operations = [
        migrations.RunPython(seed_additional_services, reverse_seed),
    ]


