# Generated by Django 5.2.8 on 2026-04-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_seed_additional_services'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='phone_number',
            new_name='phone',
        ),
        migrations.AlterField(
            model_name='booking',
            name='location',
            field=models.CharField(choices=[('victoria_island', 'Victoria Island'), ('lekki-phase1', 'Lekki Phase 1'), ('lekki-phase2', 'Lekki Phase 2'), ('ikeja-gra', 'Ikeja GRA'), ('ikoyi', 'Ikoyi'), ('surulere', 'Surulere'), ('yaba', 'Yaba'), ('other', 'Other')], default='', max_length=30),
        ),
    ]
