# Generated by Django 5.2.8 on 2026-04-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_alter_booking_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='property_size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('flat', 'Flat'), ('large_area', 'Large Area')], default='', max_length=50),
        ),
    ]
