# Generated by Django 5.2.8 on 2026-04-25 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_alter_booking_property_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='property_size',
            field=models.CharField(blank=True, choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('flat', 'Flat'), ('large_area', 'Large Area')], default=None, max_length=50, null=True),
        ),
    ]
