# Generated by Django 5.2.8 on 2026-05-01 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_alter_booking_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('service_of_interest', models.CharField(choices=[('general_cleaning', 'General Cleaning'), ('deep_cleaning', 'Deep Cleaning'), ('fumigation', 'Fumigation Services'), ('laundry', 'Laundry Services'), ('other', 'Other Inquiry')], default='other', max_length=50)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
