# Generated by Django 5.2.8 on 2026-05-01 15:42

from django.db import migrations
from decimal import Decimal

def populate_initial_prices(apps, schema_editor):
    # Use apps.get_model to avoid importing the model directly
    ServicePrice = apps.get_model('services', 'ServicePrice')
    
    initial_prices = [
        {'service_name': 'cleaning', 'base_price': Decimal('15000.00')},
        {'service_name': 'fumigation', 'base_price': Decimal('20000.00')},
        {'service_name': 'laundry_services', 'base_price': Decimal('8000.00')},
    ]

    for item in initial_prices:
        ServicePrice.objects.get_or_create(
            service_name=item['service_name'],
            defaults={'base_price': item['base_price']}
        )


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_additionalservicestwo_serviceprice'),
    ]

    operations = [
        migrations.RunPython(populate_initial_prices),
    ]
